apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
spec:
  backoffLimit: 10
  manualSelector: true
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-{{ .Chart.Name }}"
    spec:
      activeDeadlineSeconds: 180
      restartPolicy: Never
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        name: "{{ .Release.Name }}-{{ .Chart.Name }}"
        ports:
        - name: "http"
          containerPort: 80
        env:
        - name: "DOTNET_ENVIRONMENT"
          value: "{{ .Values.global.dotnetEnvironment }}"
        - name: "Redis__Configuration"
          value: "{{ .Release.Name }}-redis"
        - name: "ConnectionStrings__Default"
          value: "{{ .Values.global.connectionStrings.default | replace "[RELEASE_NAME]" .Release.Name }}"
        - name: "AbpStudioClient__StudioUrl"
          value: "{{ .Values.global.abpStudioClient.studioUrl }}"
        - name: "AbpStudioClient__IsLinkEnabled"
          value: "{{ .Values.global.abpStudioClient.isLinkEnabled }}" 
        - name: "OpenIddict__Applications__Accredi_Web__ClientId"
          value: "Accredi_Web"
        - name: "OpenIddict__Applications__Accredi_Web__ClientSecret"
          value: "{{ .Values.authServer.clientSecret }}"
        - name: "OpenIddict__Applications__Accredi_Web__RootUrl"
          value: "{{ include "accredi.hosts.web" . }}"
        - name: "OpenIddict__Applications__Accredi_Web_Public__ClientId"
          value: "Accredi_Web_Public"
        - name: "OpenIddict__Applications__Accredi_Web_Public__ClientSecret"
          value: "{{ .Values.authServer.clientSecret }}"
        - name: "OpenIddict__Applications__Accredi_Web_Public__RootUrl"
          value: "{{ include "accredi.hosts.webpublic" . }}"
        - name: "OpenIddict__Applications__Accredi_App__ClientId"
          value: "Accredi_App"
        - name: "OpenIddict__Applications__Accredi_Maui__ClientId"
          value: "Accredi_Maui"
        - name: "OpenIddict__Applications__Accredi_Swagger__ClientId"
          value: "Accredi_Swagger"
        - name: "OpenIddict__Applications__Accredi_Swagger__RootUrl"
          value: "{{ include "accredi.hosts.httpapi" . }}"
