version: '3.8'

services:
  accredi-web:
    image: accredi-web:latest
    container_name: accredi-web
    hostname: accredi-web
    build:
      context: ../../
      dockerfile: src/Accredi.Web/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=579c6938-9a6a-4a3f-9872-d678913dc471
      - App__SelfUrl=https://localhost:44353
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__IsOnK8s=true
      - AuthServer__Authority=https://localhost:44359/
      - RemoteServices__Default__BaseUrl=http://accredi-api
      - RemoteServices__AbpAccountPublic__BaseUrl=http://accredi-authserver      
      - AuthServer__MetaAddress=http://accredi-authserver
      - Redis__Configuration=redis
    ports:
      - "44353:443"
    depends_on:
      - accredi-api
    restart: on-failure
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network

  accredi-api:
    image: accredi-api:latest
    container_name: accredi-api
    hostname: accredi-api
    build:
      context: ../../
      dockerfile: src/Accredi.HttpApi.Host/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=579c6938-9a6a-4a3f-9872-d678913dc471
      - App__SelfUrl=https://localhost:44367
      - App__HealthCheckUrl=http://accredi-api/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=http://accredi-authserver
      - AuthServer__MetaAddress=https://localhost:44359
      - App__MVCPublicUrl=https://localhost:44364
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=Accredi;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    ports:
      - "44354:443"    
    depends_on:
      sql-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network
  
  accredi-authserver:
    image: accredi-authserver:latest
    container_name: accredi-authserver
    build:
      context: ../../
      dockerfile: src/Accredi.AuthServer/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - App__SelfUrl=https://localhost:44359
      - App__CorsOrigins=https://localhost:44353,https://localhost:44367
      - App__RedirectAllowedUrls=https://localhost:44353,https://localhost:44367
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=https://localhost:44359
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=579c6938-9a6a-4a3f-9872-d678913dc471
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=Accredi;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    ports:
      - "44334:443"
    depends_on:
      sql-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network

  accredi-web-public:
    image: accredi-web-public:latest
    container_name: accredi-web-public
    build:
      context: ../../
      dockerfile: src/Accredi.Web.Public/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=579c6938-9a6a-4a3f-9872-d678913dc471
      - App__SelfUrl=https://localhost:44364
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__IsOnK8s=true
      - AuthServer__Authority=https://localhost:44359/
      - RemoteServices__Default__BaseUrl=http://accredi-api         
      - AuthServer__MetaAddress=http://accredi-authserver
      - RemoteServices__AbpAccountPublic__BaseUrl=http://accredi-authserver
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=Accredi;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    ports:
      - "44306:443"
    depends_on:
      sql-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network  
  
  db-migrator:
    image: accredi-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/Accredi.DbMigrator/Dockerfile.local
    environment:
      - OpenIddict__Applications__Accredi_Web__RootUrl=https://localhost:44353
      - OpenIddict__Applications__Accredi_Swagger__RootUrl=https://localhost:44367      
      - OpenIddict__Applications__Accredi_Web_Public_Tiered__RootUrl=https://localhost:44364
      - OpenIddict__Applications__Accredi_Web_Public__RootUrl=https://localhost:44397
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=Accredi;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    restart: on-failure
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
      - abp-network
  
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "myPassw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - abp-network
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S sql-server -U sa -P "myPassw0rd" -Q "SELECT 1" -C -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - abp-network
    healthcheck:
      test: ["CMD", "redis-cli","ping"]

volumes:
  sqldata:
    name: accredi_sqldata
networks:
  abp-network:
    name: accredi-network
    driver: bridge