name: Docker Image Publisher

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      image_name:
        required: true
        type: string
      version_number:
        required: true
        type: string
        
    secrets: 
      AZURE_REGISTRY_URL:
        required: true
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}-publish

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZURE_REGISTRY_URL }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.AZURE_REGISTRY_URL }}/${{ inputs.image_name }}
          tags: |
            latest
            ${{ inputs.version_number }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./publish
          file: ./Dockerfile
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
