name: Docker Image Publisher

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      image_name:
        required: true
        type: string
      version_number:
        required: true
        type: string
        
    secrets: 
      AZURE_REGISTRY_URL:
        required: true
        
    outputs:
      version_number:
        description: "Version number of the published service"
        value: ${{ jobs.build-and-push.outputs.version_number }}

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      version_number: ${{ steps.version.outputs.version }}

    steps:
      - name: Pass version number to next job
        id: version
        run: echo "version=${{ inputs.version_number || '0.0.0' }}" >> $GITHUB_OUTPUT

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}-publish
          
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZURE_REGISTRY_URL }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.AZURE_REGISTRY_URL }}/${{ inputs.image_name }}
          tags: |
            latest
            ${{ inputs.version_number }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./publish
          file: ./Dockerfile
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
