name: Deploy Service

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      image_name:
        required: true
        type: string
      version_number:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.app_name }}
          images: ${{ secrets.AZURE_REGISTRY_URL }}/${{ inputs.image_name }}:${{ inputs.version_number }}
