name: Publish Service

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      project-path:
        required: true
        type: string
      dockerfile-path:
        required: true
        type: string
      nuget-source:
        required: true
        type: string
    outputs:
      version_number:
        description: "Version number of the published service"
        value: ${{ jobs.publish.outputs.version_number }}

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      version_number: ${{ steps.version.outputs.version }}

    steps:
      - name: Pass version number to next job
        id: version
        run: echo "version=${{ inputs.version_number || '0.0.0' }}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.x
            8.x

      - name: Install Tools
        run: |
          dotnet tool install -g dotnet-setversion
          dotnet tool install -g Volo.Abp.Studio.Cli

      - name: Install Libs
        run: abp install-libs

      - name: Add nuget repo
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.PAT_TOKEN }} --store-password-in-clear-text --name github "${{ inputs.nuget-source }}"

      - name: Set version
        run: setversion ${{ inputs.version_number }} ..\..\common.props

      - name: Publish
        run: dotnet publish ${{ inputs.project-path }} -c Release -o output/publish

      - name: Copy Dockerfile
        run: cp ${{ inputs.dockerfile-path }} output/Dockerfile

      - name: Upload Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.service-name }}-publish
          path: output
          overwrite: true
