name: Publish Docker image

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  
  build-solution:
    name: Build & test solution
    runs-on: ubuntu-latest
    outputs:
      version_number: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            9.x
            8.x

      - name: Get next version
        uses: reecetech/version-increment@2024.4.3
        id: version
        with:
          scheme: conventional_commits
          increment: patch

      - name: Add nuget repo
        run: dotnet nuget add source --username USERNAME --password ${{secrets.PAT_TOKEN}} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/AccrediWorks/index.json"
       
      - name: Build Solution
        run: dotnet build -c Release

      - name: Run tests
        run: dotnet test --configuration Release --no-build
  
  
  publish-portal:
    name: Publish web service
    uses: ./.github/workflows/publish-service.yml
    needs: build-solution
    with:
      service_name: web
      project_path: src/Accredi.Web.Portal
      dockerfile_path: src/Accredi.Web.Portal/Dockerfile
      nuget_source: https://nuget.pkg.github.com/AccrediWorks/index.json
      version_number: ${{ needs.build-solution.outputs.version_number }}
    secrets: inherit
    
  publish-api:
    name: Publish api service
    uses: ./.github/workflows/publish-service.yml
    needs: build-solution
    with:
      service_name: api
      project_path: src/Accredi.HttpApi.Host
      dockerfile_path: src/Accredi.HttpApi.Host/Dockerfile
      nuget_source: https://nuget.pkg.github.com/AccrediWorks/index.json
      version_number: ${{ needs.build-solution.outputs.version_number }}
    secrets: inherit
    
  publish-account:
    name: Publish auth service
    uses: ./.github/workflows/publish-service.yml
    needs: build-solution
    with:
      service_name: auth
      project_path: src/Accredi.AuthServer
      dockerfile_path: src/Accredi.AuthServer/Dockerfile
      nuget_source: https://nuget.pkg.github.com/AccrediWorks/index.json
      version_number: ${{ needs.build-solution.outputs.version_number }}
    secrets: inherit

  docker-portal:
    name: Package web
    needs: [ "publish-portal" ]
    uses: ./.github/workflows/build-docker-image.yml
    with:
      artifact_name: web
      image_name: accredi-portal
      version_number: ${{ needs.publish-portal.outputs.version_number }}
    secrets: inherit

  docker-api:
    name: Package api
    needs: [ "publish-api" ]
    uses: ./.github/workflows/build-docker-image.yml
    with:
      artifact_name: api
      image_name: accredi-api
      version_number: ${{ needs.publish-api.outputs.version_number }}
    secrets: inherit

  docker-account:
    name: Package auth
    needs: [ "publish-account" ]
    uses: ./.github/workflows/build-docker-image.yml
    with:
      artifact_name: auth
      image_name: accredi-account
      version_number: ${{ needs.publish-account.outputs.version_number }}
    secrets: inherit

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [ "docker-portal","docker-api" ,"docker-account"]

    steps:
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ needs.docker-account.outputs.version_number }}
          name: Release ${{ needs.docker-account.outputs.version_number }}
  
  deploy-portal:
    needs: [ "release" ]
    uses: ./.github/workflows/deploy-service.yml
    with:
      app_name: accredi-portal
      image_name: accredi-portal
      version_number: ${{ needs.build-solution.outputs.version_number }}
    secrets: inherit
  
  deploy-api:
    needs: [ "release" ]
    uses: ./.github/workflows/deploy-service.yml
    with:
      app_name: accredi-api
      image_name: accredi-api
      version_number: ${{ needs.build-solution.outputs.version_number }}
    secrets: inherit
      
  deploy-account:
    needs: [ "release" ]
    uses: ./.github/workflows/deploy-service.yml
    with:
      app_name: accredi-account
      image_name: accredi-account
      version_number: ${{ needs.build-solution.outputs.version_number }}
    secrets: inherit